document.writeln("<ul>");
document.writeln("<li>背景：");
document.writeln("<input id=\"bg1\" onclick=\"setBG('#dcecf5')\" type=\"button\" class=\"setBG\" />");
document.writeln("<input id=\"bg2\" onclick=\"setBG('#e1ffe6')\" type=\"button\" class=\"setBG\" />");
document.writeln("<input id=\"bg3\" onclick=\"setBG('#edf6d0')\" type=\"button\" class=\"setBG\" />");
document.writeln("<input id=\"bg4\" onclick=\"setBG('#eae8f7')\" type=\"button\" class=\"setBG\" />");
document.writeln("<input id=\"bg5\" onclick=\"setBG('#f5f1e7')\" type=\"button\" class=\"setBG\" />");
document.writeln("<input id=\"bg6\" onclick=\"setBG('#ebf4ef')\" type=\"button\" class=\"setBG\" />");
document.writeln("<input id=\"bg7\" onclick=\"setBG('#FFFFFF')\" type=\"button\" class=\"setBG\" />");
document.writeln("</li>");
document.writeln("<li><span class=\"l\">字体大小：</span>");
document.writeln("<div class=\"setFont l\"> <span id=\"fontWidth\"></span>");
document.writeln("<input id=\"fontBtn\" type=\"button\">");
document.writeln("</span> <span id=\"fontVal\">14</span> </div>");
document.writeln("<li> 字体颜色：");
document.writeln("<select onchange=\"setFontColor(this.value)\" id=\"txtcolor\" name=\"txtcolor\">");
document.writeln("<option value=\"#000000\">黑色</option>");
document.writeln("<option value=\"#ff0000\">红色</option>");
document.writeln("<option value=\"#006600\">绿色</option>");
document.writeln("<option value=\"#0000ff\">蓝色</option>");
document.writeln("<option value=\"#660000\">棕色</option>");
document.writeln("</select>");
document.writeln("</li>");
document.writeln("<li>风格：");
document.writeln("<input name=\"setStyle\" type=\"radio\" onclick=\"setStyle(this.value)\" value=\"0\" checked=\"checked\" />");
document.writeln("经典");
document.writeln("<input name=\"setStyle\" onclick=\"setStyle(this.value)\" type=\"radio\" value=\"1\" />");
document.writeln("全屏</li>");
document.writeln("<li id=\"sudu\">滚动速度：<a id=\"sudu50\" href=\"javascript:setSpeed(50);\">快</a><a id=\"sudu100\" href=\"javascript:setSpeed(100);\" class=\"this\">中</a><a id=\"sudu150\" href=\"javascript:setSpeed(150);\">慢</a></li>");
document.writeln("</ul>");